<script lang="ts">
  import { engineStore } from '../lib/stores/engineStore';
  import { calculateSimulation, calculateMarketFit } from '../features/digital/lib/simulator';
  import * as Card from "$lib/components/ui/card";
  import { Button } from "$lib/components/ui/button";
  import { Badge } from "$lib/components/ui/badge";
  import { Separator } from "$lib/components/ui/separator";
  import { Download, FileText, Share2, Printer, CheckCircle2, AlertTriangle, Target, Briefcase, Zap } from "@lucide/svelte";

  let state = $derived($engineStore);
  let economics = $derived(calculateSimulation(state.economics));
  let marketFit = $derived(calculateMarketFit(state));

  function exportMarkdown() {
    const content = `
# Strategic Marketing Report: ${state.strategy.brandName || 'Unnamed Project'}
Date: ${new Date().toLocaleDateString()}
Market Fit Score: ${marketFit}%

## 1. Strategic Foundations (SWOT)
### Strengths
${state.strategy.swot.strengths.map(s => `- ${s}`).join('\n')}
### Weaknesses
${state.strategy.swot.weaknesses.map(s => `- ${s}`).join('\n')}
### Opportunities
${state.strategy.swot.opportunities.map(s => `- ${s}`).join('\n')}
### Threats
${state.strategy.swot.threats.map(s => `- ${s}`).join('\n')}

## 2. Buyer Persona: ${state.persona?.name || 'Not defined'}
- **Archetype**: ${state.persona?.archetype || 'N/A'}
- **Goals**: ${state.persona?.goals.join(', ') || 'N/A'}
- **Pain Points**: ${state.persona?.painPoints.join(', ') || 'N/A'}

## 3. Unit Economics
- **LTV**: $${economics.ltv.toFixed(2)}
- **CAC**: $${state.economics.cac}
- **LTV/CAC Ratio**: ${economics.ltvCacRatio.toFixed(2)}x
- **Payback Period**: ${economics.paybackPeriod || 'N/A'} months
- **Sustainability**: ${economics.isSustainable ? 'High' : 'At Risk'}

## 4. Communication Strategy
- **SEO Title**: ${state.media.seo.title}
- **Target Channels**: ${Object.entries(state.media.omnichannel).filter(([_, v]) => v).map(([k]) => k).join(', ')}
    `;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `strategic-report-${new Date().getTime()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
</script>

<div class="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700 print:m-0 print:p-0">
  <!-- Top Bar -->
  <div class="flex flex-col sm:flex-row gap-4 justify-between items-start sm:items-center bg-slate-900/50 p-6 rounded-3xl border border-slate-800 print:bg-white print:text-black print:border-black">
    <div class="flex items-center gap-4">
        <div class="h-16 w-16 rounded-2xl bg-blue-600 flex items-center justify-center text-white shadow-lg shadow-blue-600/20 print:shadow-none">
            <FileText class="w-8 h-8" />
        </div>
        <div>
            <h2 class="text-2xl font-bold text-white tracking-tight print:text-black">{state.strategy.brandName || 'New Venture Strategy'}</h2>
            <p class="text-sm text-slate-500 print:text-gray-600">Generated by Marketing Engine AI | {new Date(state.lastUpdated).toLocaleString()}</p>
        </div>
    </div>
    <div class="flex gap-2 print:hidden">
        <Button variant="outline" class="border-slate-700 hover:bg-slate-800" onclick={() => window.print()}>
            <Printer class="w-4 h-4 mr-2" /> Export PDF
        </Button>
        <Button class="bg-blue-600 hover:bg-blue-500 shadow-lg shadow-blue-600/20" onclick={exportMarkdown}>
            <Download class="w-4 h-4 mr-2" /> Export MD
        </Button>
    </div>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
    <!-- Left Column: Strategy & Persona -->
    <div class="md:col-span-2 space-y-8">
        <Card.Root class="bg-slate-900/40 border-slate-800/80 backdrop-blur-md overflow-hidden print:bg-white print:text-black print:border-black">
            <Card.Header class="bg-slate-900/60 border-b border-slate-800 print:bg-gray-100 print:border-black">
                <Card.Title class="text-lg flex items-center gap-2 print:text-black">
                    <Target class="w-5 h-5 text-blue-400 print:text-blue-600" /> Strategic Analysis
                </Card.Title>
            </Card.Header>
            <Card.Content class="p-6">
                <div class="grid grid-cols-2 gap-8">
                    <div class="space-y-4">
                        <h4 class="text-[10px] font-bold text-slate-500 uppercase tracking-widest print:text-gray-600">Strengths Matrix</h4>
                        <div class="flex flex-wrap gap-2">
                            {#each state.strategy.swot.strengths as s}
                                <Badge variant="outline" class="bg-emerald-500/5 border-emerald-500/20 text-emerald-400 print:bg-white print:border-black print:text-black">{s}</Badge>
                            {/each}
                        </div>
                    </div>
                    <div class="space-y-4">
                        <h4 class="text-[10px] font-bold text-slate-500 uppercase tracking-widest print:text-gray-600">Target Segment</h4>
                        {#if state.persona}
                            <div class="text-white font-bold print:text-black">{state.persona.name}</div>
                            <div class="text-xs text-slate-400 print:text-gray-700">{state.persona.archetype}</div>
                        {/if}
                    </div>
                </div>
            </Card.Content>
        </Card.Root>

        <Card.Root class="bg-slate-900/40 border-slate-800/80 backdrop-blur-md print:bg-white print:text-black print:border-black">
            <Card.Header class="bg-slate-900/60 border-b border-slate-800 print:bg-gray-100 print:border-black">
                <Card.Title class="text-lg flex items-center gap-2 print:text-black">
                    <Briefcase class="w-5 h-5 text-indigo-400 print:text-indigo-600" /> Marketing Mix (4Ps)
                </Card.Title>
            </Card.Header>
            <Card.Content class="p-6 grid grid-cols-1 sm:grid-cols-2 gap-6">
                {#each Object.entries(state.strategy.marketingMix) as [p, val]}
                    <div class="space-y-2">
                        <h5 class="text-[10px] font-bold text-slate-500 uppercase tracking-widest print:text-gray-600">{p}</h5>
                        <p class="text-sm text-slate-300 print:text-black">{val || 'Not defined'}</p>
                    </div>
                {/each}
            </Card.Content>
        </Card.Root>
    </div>

    <!-- Right Column: Scores & Metrics -->
    <div class="space-y-8">
        <Card.Root class="bg-blue-600 text-white shadow-xl shadow-blue-600/20 overflow-hidden relative print:bg-white print:text-black print:border-black print:shadow-none">
            <div class="absolute -bottom-12 -right-12 w-48 h-48 bg-white/10 rounded-full blur-3xl print:hidden"></div>
            <Card.Header>
                <Card.Title class="text-white/80 text-xs font-bold uppercase tracking-widest print:text-gray-600">Market Fit Score</Card.Title>
            </Card.Header>
            <Card.Content class="pt-0 pb-8 text-center">
                <div class="text-7xl font-black mb-2 print:text-blue-600">{marketFit}%</div>
            </Card.Content>
        </Card.Root>

        <Card.Root class="bg-slate-900/40 border-slate-800/80 backdrop-blur-md print:bg-white print:text-black print:border-black">
            <Card.Header>
                <Card.Title class="text-lg flex items-center gap-2 print:text-black">
                    <Zap class="w-5 h-5 text-emerald-400 print:text-emerald-600" /> Unit Economics
                </Card.Title>
            </Card.Header>
            <Card.Content class="p-6 space-y-6">
                <div class="flex justify-between items-center">
                    <span class="text-sm text-slate-400 print:text-gray-600">LTV/CAC</span>
                    <span class="text-xl font-bold {economics.ltvCacRatio >= 3 ? 'text-emerald-400' : 'text-rose-400'} print:text-black">{economics.ltvCacRatio.toFixed(2)}x</span>
                </div>
                <Separator class="bg-slate-800 print:bg-black" />
                <div class="flex justify-between items-center">
                    <span class="text-sm text-slate-400 print:text-gray-600">Payback</span>
                    <span class="text-white font-medium print:text-black">{economics.paybackPeriod ? `${economics.paybackPeriod} mo.` : 'N/A'}</span>
                </div>
            </Card.Content>
        </Card.Root>
    </div>
  </div>
</div>

<style>
    @media print {
        :global(body) {
            background: white !important;
            color: black !important;
        }
        :global(nav) {
            display: none !important;
        }
    }
</style>
